/*
MySQL script (Workbench 8) to upload raw text files as received by NHS England 

This script sets up individual level Admitted Patient Care (APC) Hospital Episode Statistics (HES) data 
This data release was approved as part of NIC-393510
Data was received as pipe-delimited flat text files for each financial year  

Editor: Linda Wijlaars
Version: 2023_1
Date: 16 January 2024
Original author: Grant Thiltgen
*/

--set up table and variables types 
CREATE TABLE hes_ons.APC_2223 (
acscflag tinyint,
activage  smallint,
admiage smallint, 
admidate date, 
admimeth varchar(8),
admincat smallint,
admincatst  smallint,
admisorc  smallint,
admistat varchar(5), 
aekey varchar(20),
alcbrddiag varchar(4),
alcbrdfrac double,
alcdiag varchar(6),
alcdiag_4 char(4), 
alcfrac double,
alcnrwdiag varchar(4),
alcnrwfrac double,
anagest  smallint,
anasdate date,
antedur smallint,
at_gp_practice char(3), 
at_residence char(3),
at_treatment char(3), 
bedyear  smallint,
biresus_1 smallint,
biresus_2 smallint,
biresus_3 smallint,
biresus_4 smallint,
biresus_5 smallint,
biresus_6 smallint,
biresus_7 smallint,
biresus_8 smallint,
biresus_9 smallint,
birordr_1 varchar(5),
birordr_2 varchar(5),
birordr_3 varchar(5),
birordr_4 varchar(5),
birordr_5 varchar(5),
birordr_6 varchar(5),
birordr_7 varchar(5),
birordr_8 varchar(5),
birordr_9 varchar(5),
birstat_1 smallint,
birstat_2 smallint,
birstat_3 smallint,
birstat_4 smallint,
birstat_5 smallint,
birstat_6 smallint,
birstat_7 smallint,
birstat_8 smallint, 
birstat_9 smallint,
birweit_1 smallint,
birweit_2 smallint,
birweit_3 smallint,
birweit_4 smallint,
birweit_5 smallint,
birweit_6 smallint,
birweit_7 smallint,
birweit_8 smallint,
birweit_9 smallint,
cannet varchar(3), 
canreg varchar(5), 
carersi smallint,
category smallint,
cause  varchar(6),
ccg_gp_practice varchar(5),
ccg_residence varchar(5),
ccg_responsibility varchar(5), 
ccg_responsibility_origin  smallint,
ccg_treatment varchar(5), 
ccg_treatment_origin smallint,
cdsextdate date ,
cdsverprotid smallint,
cdsversion varchar(6), 
cendur smallint,
censage smallint,
censtat smallint,
cenward varchar(12),
classpat smallint,
cr_gp_practice char(3),
cr_residence char(3), 
cr_treatment char(3), 
csnum varchar(9),
currward varchar(3), 
currward_ons varchar(9), 
delchang smallint,
delinten smallint,
delmeth_1 varchar(5), 
delmeth_2 varchar(5), 
delmeth_3 varchar(5), 
delmeth_4 varchar(5), 
delmeth_5 varchar(5), 
delmeth_6 varchar(5), 
delmeth_7 varchar(5), 
delmeth_8 varchar(5), 
delmeth_9 varchar(5), 
delmeth_d varchar(5), 
delonset  smallint,
delplac_1 smallint, 
delplac_2 smallint, 
delplac_3 smallint, 
delplac_4 smallint, 
delplac_5 smallint, 
delplac_6 smallint, 
delplac_7 smallint, 
delplac_8 smallint, 
delplac_9 smallint, 
delposan smallint,
delprean smallint,
delstat_1 smallint,
delstat_2 smallint,
delstat_3 smallint,
delstat_4 smallint,
delstat_5 smallint,
delstat_6 smallint,
delstat_7 smallint,
delstat_8 smallint,
delstat_9 smallint,
detdur smallint,
detndate date,
diag_01 varchar(6),
diag_02 varchar(6),
diag_03 varchar(6),
diag_04 varchar(6),
diag_05 varchar(6),
diag_06 varchar(6),
diag_07 varchar(6),
diag_08 varchar(6),
diag_09 varchar(6),
diag_10 varchar(6),
diag_11 varchar(6),
diag_12 varchar(6),
diag_13 varchar(6),
diag_14 varchar(6),
diag_15 varchar(6),
diag_16 varchar(6),
diag_17 varchar(6),
diag_18 varchar(6),
diag_19 varchar(6),
diag_20 varchar(6),
diag_3_concat varchar(120),
diag_4_concat varchar(120),
diag_count smallint,
disdate date, 
disdest  smallint,
dismeth  smallint,
disreadydate date,
domproc char(4),
earldatoff date,
elecdate date,
elecdur  smallint,
elecdur_calc smallint,
endage smallint,
epidur  smallint,
epiend date, 
epikey varchar(20),
epiorder smallint,
epistart date, 
epistat smallint,
epitype smallint,
ethnos varchar(5),
ethraw varchar(1),
fae  smallint,
fae_emergency smallint,
fce smallint,
fde smallint,
firstreg varchar(5),
fyear  smallint,
gestat_1 smallint,
gestat_2 smallint,
gestat_3 smallint,
gestat_4 smallint,
gestat_5 smallint,
gestat_6 smallint,
gestat_7 smallint,
gestat_8 smallint,
gestat_9 smallint,
gortreat char(1),
gpprac char(6),
gppracha char(3),
gppracro char(3), 
gpprpct char(5), 
gpprstha char(3), 
hatreat char(3), 
hneoind varchar(2),
hrg40 char(3), 
hrglate35 smallint,
hrgnhs varchar(5), 
hrgnhsvn varchar(5),
imd04 double,
imd04_decile char(30),
imd04c double,
imd04ed double,
imd04em double,
imd04hd double,
imd04hs double,
imd04i double,
imd04ia double,
imd04ic double,
imd04le double,
imd04rk mediumint,
intmanig smallint,
lsoa01 char(9),
lsoa11 char(9),
mainspef varchar(5),
marstat varchar(5),
matage smallint,
maternity_episode_type smallint,
mentcat varchar(5), 
msoa01 char(9),
msoa11 char(9), 
mydob mediumint, 
neocare varchar(5),
neodur  smallint,
newnhsno_check varchar(1), 
nhsnoind varchar(5),
numbaby varchar(5), 
numpreg  smallint,
numtailb smallint,
oacode6 char(6), 
opcs43 char(1), 
opdate_01 date,
opdate_02 date,
opdate_03 date,
opdate_04 date,
opdate_05 date,
opdate_06 date,
opdate_07 date,
opdate_08 date,
opdate_09 date,
opdate_10 date,
opdate_11 date, 
opdate_12 date,
opdate_13 date,
opdate_14 date,
opdate_15 date, 
opdate_16 date,
opdate_17 date,
opdate_18 date,
opdate_19 date,
opdate_20 date,
opdate_21 date,
opdate_22 date,
opdate_23 date,
opdate_24 date,
operstat varchar(5),
opertn_01 char(4),
opertn_02 char(4),
opertn_03 char(4),
opertn_04 char(4),
opertn_05 char(4),
opertn_06 char(4),
opertn_07 char(4),
opertn_08 char(4),
opertn_09 char(4),
opertn_10 char(4),
opertn_11 char(4),
opertn_12 char(4),
opertn_13 char(4),
opertn_14 char(4),
opertn_15 char(4),
opertn_16 char(4),
opertn_17 char(4),
opertn_18 char(4),
opertn_19 char(4),
opertn_20 char(4),
opertn_21 char(4),
opertn_22 char(4),
opertn_23 char(4),
opertn_24 char(4),
opertn_3_concat varchar(96),
opertn_4_concat varchar(125),
opertn_count smallint,
orgpppid varchar(6),
partyear mediumint,
pcfound varchar(3),
pcgcode varchar(8),
pcgorig smallint,
pcon char(3),
pcon_ons varchar(9),
pconsult char(16), 
pctcode_his varchar(5),
pctcode02 varchar(5),
pctcode06 varchar(5),
pctnhs varchar(5), 
pctorig_his smallint,
pctorig02 smallint,
pctorig06 smallint,
pcttreat varchar(5), 
posopdur smallint,
postdist char(4),
postdur smallint,
preferer char(16), 
preggmp char(16), 
preopdur smallint,
primercp varchar(5), 
procode char(5),
procode3 varchar(5),
procode5 varchar(5),
procodet varchar(5), 
protype varchar(15), 
provspnops char(20),
purcode varchar(5), 
purro varchar(5),
purstha char(3),
purval  smallint,
referorg varchar(8), 
rescty varchar(5), 
rescty_ons varchar(9),
resgor char(1), 
resgor_ons varchar(9),
resha char(3), 
resladst char(4), 
resladst_ons char(4), 
respct_his varchar(5), 
respct02 varchar(5),
respct06 varchar(5), 
resro char(3), 
resstha_his char(3),
resstha02 char(3),
resstha06 char(3), 
rotreat char(3), 
rttperend date,
rttperstart date,
rttperstat smallint,
rururb_ind  smallint,
sender varchar(5), 
sex  smallint,
sexbaby_1 varchar(5),
sexbaby_2 varchar(5),
sexbaby_3 varchar(5),
sexbaby_4 varchar(5),
sexbaby_5 varchar(5),
sexbaby_6 varchar(5),
sexbaby_7 varchar(5),
sexbaby_8 varchar(5),
sexbaby_9 varchar(5),
sitetret char(5),
spelbgin  smallint,
speldur  smallint,
spelend char,
startage smallint,
sthatret char(3), 
subdate date,
suscorehrg char(5),
sushrg char(5),
sushrgvers  smallint,
suslddate date,
susrecid varchar(20),
susspellid varchar(19),
tokenid char(15),
tretspef varchar(5), 
vind smallint,
waitdays mediumint,
waitlist smallint,
ward91 char(6), 
ward98 char(6),
wardstrt varchar(9),
well_baby_ind char(1)
);

--load data onto SQL server

SET GLOBAL local_infile = TRUE;

LOAD DATA LOCAL INFILE '[filepath]/Data/APC/NIC393510_HES_APC_202299.txt'
INTO TABLE hes_ons.APC_2223
fields terminated by "|"
lines terminated by "\n"
ignore 1 lines 
(@acscflag, @activage, 	@admiage, 	@admidate, 	@admimeth, 	@admincat, 	@admincatst, 	@admisorc, 	@admistat, @aekey, 	@alcbrddiag, @alcbrdfrac,
@alcdiag,	@alcdiag_4, @alcfrac, 	@alcnrwdiag, @alcnrwfrac,
@anagest, 	@anasdate, 	@antedur, 	@at_gp_practice, 	@at_residence, 	@at_treatment, 	@bedyear, 	@biresus_1, 	@biresus_2, 	@biresus_3, 	@biresus_4, 	
@biresus_5, 	@biresus_6, 	@biresus_7, 	@biresus_8, 	@biresus_9, 	@birordr_1, 	@birordr_2, 	@birordr_3, 	@birordr_4, 	@birordr_5, 	@birordr_6, 	
@birordr_7, 	@birordr_8, 	@birordr_9, 	@birstat_1, 	@birstat_2, 	@birstat_3, 	@birstat_4, 	@birstat_5, 	@birstat_6, 	@birstat_7, 	@birstat_8, 	
@birstat_9, 	@birweit_1, 	@birweit_2, 	@birweit_3, 	@birweit_4, 	@birweit_5, 	@birweit_6, 	@birweit_7, 	@birweit_8, 	@birweit_9, 	@cannet, 	
@canreg, 	@carersi, 	@category, 	@cause,	@ccg_gp_practice, 	@ccg_residence, 	@ccg_responsibility, 	@ccg_responsibility_origin, 	
@ccg_treatment, 	@ccg_treatment_origin, 	@cdsextdate, @cdsverprotid,
@cdsversion, 	@cendur, 	@censage, 	@censtat, 	@cenward, 	@classpat, 	@cr_gp_practice, 	@cr_residence, 	@cr_treatment, 	
@csnum, 	@currward, @currward_ons,	@delchang, 	@delinten,	@delmeth_1, 	@delmeth_2, 	@delmeth_3, 	@delmeth_4, 	@delmeth_5, 	@delmeth_6, 	@delmeth_7, 	
@delmeth_8, 	@delmeth_9,  	@delmeth_d, 	@delplac_1, 	@delplac_2, 	@delplac_3, 	@delplac_4, 	@delplac_5, 	@delplac_6, 	@delplac_7, 	@delplac_8, 	
@delplac_9, @delonset, 	@delposan, 	@delprean, 	@delstat_1, 	@delstat_2, 	@delstat_3, 	@delstat_4, 	@delstat_5, 	@delstat_6, 	@delstat_7, 
@delstat_8, 	@delstat_9, 	@detdur, 	@detndate, 	@diag_01, 	@diag_02, 	@diag_03, 	@diag_04, 	@diag_05, 	@diag_06, 	@diag_07, 	@diag_08, 	@diag_09, 	@diag_10, 	
@diag_11, 	@diag_12, 	@diag_13, 	@diag_14, 	@diag_15, 	@diag_16, 	@diag_17, 	@diag_18, 	@diag_19, 	@diag_20, @diag_3_concat, @diag_4_concat, @diag_count,
@disdate, 	@disdest, 	@dismeth, 	@disreadydate, 	@domproc, 	@earldatoff, @elecdate, 	@elecdur, 	@elecdur_calc,  
@endage,  @epidur, 	@epiend, 	@epikey, 	@epiorder, 	@epistart, 	@epistat, 	@epitype, 	@ethnos, @ethraw,	
@fae, 	@fae_emergency, 	@fce, 	@fde, 	@firstreg, 	@fyear, 	
@gestat_1, 	@gestat_2, 	@gestat_3, 	@gestat_4, 	@gestat_5, 	@gestat_6, 	@gestat_7, 	@gestat_8, 	@gestat_9, 	@gortreat, 	@gpprac, 	@gppracha, 	@gppracro,
@gpprpct, 	@gpprstha, 	
@hatreat, 	@hneoind, @hrg40, 	@hrglate35, @hrgnhs, 	@hrgnhsvn, 	@imd04, 	@imd04_decile, 	@imd04c, 	@imd04ed, 	@imd04em, 	@imd04hd, 	@imd04hs, 	@imd04i, 	
@imd04ia, 	@imd04ic, 	@imd04le, 	@imd04rk, 	@intmanig, 	@lsoa01, 	@lsoa11, 	
@mainspef, 	@marstat, 	@matage, 	@maternity_episode_type, @mentcat, 	@msoa01, 	@msoa11, 	@mydob, 	
@neocare, @neodur, 	@newnhsno_check, @nhsnoind, 	@numbaby, 	@numpreg, 	@numtailb, 	
@oacode6, 	@opcs43, 	@opdate_01, 	@opdate_02, 	@opdate_03, 	@opdate_04, 	@opdate_05, 	@opdate_06,
@opdate_07, 	@opdate_08, 	@opdate_09, 	@opdate_10, 	@opdate_11, 	@opdate_12, 	@opdate_13, 	@opdate_14, 	@opdate_15, 	@opdate_16, 	@opdate_17, 	
@opdate_18, 	@opdate_19, 	@opdate_20, 	@opdate_21, 	@opdate_22, 	@opdate_23, 	@opdate_24, 	
@operstat, 	@opertn_01, @opertn_02, @opertn_03, @opertn_04, @opertn_05, @opertn_06, @opertn_07, @opertn_08, @opertn_09, @opertn_10, @opertn_11, @opertn_12, 
@opertn_13, @opertn_14, @opertn_15, @opertn_16, @opertn_17, @opertn_18, @opertn_19, @opertn_20, @opertn_21, @opertn_22, @opertn_23, @opertn_24, 
@opertn_3_concat, @opertn_4_concat, @opertn_count, 	@orgpppid,
@partyear, 	@pcfound, 	@pcgcode, 	
@pcgorig, 	@pcon, 	@pcon_ons, 	@pconsult, 	@pctcode_his, 	@pctcode02, 	@pctcode06, 	@pctnhs, 	@pctorig_his, 	@pctorig02, 	@pctorig06, 	@pcttreat, 	@posopdur, 	
@postdist, 	@postdur, 	@preferer, 	@preggmp, 	@preopdur, 	@primercp, 	@procode, 	@procode3, 	@procode5, @procodet, 	@protype, 	@provspnops, 	@purcode, 	@purro, 	@purstha, 	
@purval, 	
@referorg, 	@rescty, 	@rescty_ons, @resgor, @resgor_ons,	@resha, 	@resladst, @resladst_ons,	@respct_his, 	@respct02, 	@respct06, 	@resro, 	@resstha_his, 	@resstha02, 	@resstha06, 	
@rotreat, 	@rttperend, @rttperstart, @rttperstat,
@rururb_ind, 	@sender, 	@sex, 	@sexbaby_1, 	@sexbaby_2, 	@sexbaby_3, 	@sexbaby_4, 	@sexbaby_5, 	@sexbaby_6, 	@sexbaby_7, 	@sexbaby_8, 	
@sexbaby_9, 	@sitetret, 	@spelbgin, 	@speldur, 	@spelend, 	@startage, 	@sthatret, 	@subdate, 	@suscorehrg, 	@sushrg, 	@sushrgvers, 	@suslddate, 	@susrecid, 	@susspellid, @tokenid,
@tretspef, 	@vind, 	@waitdays, @waitlist,	@ward91, @ward98,	@wardstrt, 	@well_baby_ind)
SET
acscflag = nullif(@acscflag,''),
activage = nullif(@activage,''),
admiage = nullif(@admiage,''),
admidate = nullif(@admidate,''),
admimeth = nullif(@admimeth,''),
admincat = nullif(@admincat,''),
admincatst = nullif(@admincatst,''),
admisorc = nullif(@admisorc,''),
admistat = nullif(@admistat,''),
aekey = nullif(@aekey,''),
alcbrddiag = nullif(@alcbrddiag,''),
alcbrdfrac = nullif(@alcbrdfrac,''),
alcdiag  = nullif(@alcdiag,''),
alcdiag_4 = nullif(@alcdiag_4,''),
alcfrac = nullif(@alcfrac,''),
alcnrwdiag = nullif(@alcnrwdiag,''),
alcnrwfrac  = nullif(@alcnrwfrac,''),
anagest = nullif(@anagest,''),
anasdate = nullif(@anasdate,''),
antedur = nullif(@antedur,''),
at_gp_practice = nullif(@at_gp_practice,''),
at_residence = nullif(@at_residence,''),
at_treatment = nullif(@at_treatment,''),
bedyear = nullif(@bedyear,''),
biresus_1 = nullif(@biresus_1,''),
biresus_2 = nullif(@biresus_2,''),
biresus_3 = nullif(@biresus_3,''),
biresus_4 = nullif(@biresus_4,''),
biresus_5 = nullif(@biresus_5,''),
biresus_6 = nullif(@biresus_6,''),
biresus_7 = nullif(@biresus_7,''),
biresus_8 = nullif(@biresus_8,''),
biresus_9 = nullif(@biresus_9,''),
birordr_1 = nullif(@birordr_1,''),
birordr_2 = nullif(@birordr_2,''),
birordr_3 = nullif(@birordr_3,''),
birordr_4 = nullif(@birordr_4,''),
birordr_5 = nullif(@birordr_5,''),
birordr_6 = nullif(@birordr_6,''),
birordr_7 = nullif(@birordr_7,''),
birordr_8 = nullif(@birordr_8,''),
birordr_9 = nullif(@birordr_9,''),
birstat_1 = nullif(@birstat_1,''),
birstat_2 = nullif(@birstat_2,''),
birstat_3 = nullif(@birstat_3,''),
birstat_4 = nullif(@birstat_4,''),
birstat_5 = nullif(@birstat_5,''),
birstat_6 = nullif(@birstat_6,''),
birstat_7 = nullif(@birstat_7,''),
birstat_8 = nullif(@birstat_8,''),
birstat_9 = nullif(@birstat_9,''),
birweit_1 = nullif(@birweit_1,''),
birweit_2 = nullif(@birweit_2,''),
birweit_3 = nullif(@birweit_3,''),
birweit_4 = nullif(@birweit_4,''),
birweit_5 = nullif(@birweit_5,''),
birweit_6 = nullif(@birweit_6,''),
birweit_7 = nullif(@birweit_7,''),
birweit_8 = nullif(@birweit_8,''),
birweit_9 = nullif(@birweit_9,''),
cannet = nullif(@cannet,''),
canreg = nullif(@canreg,''),
carersi = nullif(@carersi,''),
category = nullif(@category,''),
cause = nullif(@cause,''),
ccg_gp_practice = nullif(@ccg_gp_practice,''),
ccg_residence = nullif(@ccg_residence,''),
ccg_responsibility = nullif(@ccg_responsibility,''),
ccg_responsibility_origin = nullif(@ccg_responsibility_origin,''),
ccg_treatment = nullif(@ccg_treatment,''),
ccg_treatment_origin = nullif(@ccg_treatment_origin,''),
cdsextdate = nullif(@cdsextdate,''),
cdsverprotid = nullif(@cdsverprotid,''),
cdsversion = nullif(@cdsversion,''),
cendur = nullif(@cendur,''),
censage = nullif(@censage,''),
censtat = nullif(@censtat,''),
cenward = nullif(@cenward,''),
classpat = nullif(@classpat,''),
cr_gp_practice = nullif(@cr_gp_practice,''),
cr_residence = nullif(@cr_residence,''),
cr_treatment = nullif(@cr_treatment,''),
csnum = nullif(@csnum,''),
currward = nullif(@currward,''),
currward_ons = nullif(@currward_ons,''),
delchang = nullif(@delchang,''),
delinten = nullif(@delinten,''),
delmeth_1 = nullif(@delmeth_1,''),
delmeth_2 = nullif(@delmeth_2,''),
delmeth_3 = nullif(@delmeth_3,''),
delmeth_4 = nullif(@delmeth_4,''),
delmeth_5 = nullif(@delmeth_5,''),
delmeth_6 = nullif(@delmeth_6,''),
delmeth_7 = nullif(@delmeth_7,''),
delmeth_8 = nullif(@delmeth_8,''),
delmeth_9 = nullif(@delmeth_9,''),
delmeth_d = nullif(@delmeth_d,''),
delonset = nullif(@delonset,''),
delplac_1 = nullif(@delplac_1,''),
delplac_2 = nullif(@delplac_2,''),
delplac_3 = nullif(@delplac_3,''),
delplac_4 = nullif(@delplac_4,''),
delplac_5 = nullif(@delplac_5,''),
delplac_6 = nullif(@delplac_6,''),
delplac_7 = nullif(@delplac_7,''),
delplac_8 = nullif(@delplac_8,''),
delplac_9 = nullif(@delplac_9,''),
delposan = nullif(@delposan,''),
delprean = nullif(@delprean,''),
delstat_1 = nullif(@delstat_1,''),
delstat_2 = nullif(@delstat_2,''),
delstat_3 = nullif(@delstat_3,''),
delstat_4 = nullif(@delstat_4,''),
delstat_5 = nullif(@delstat_5,''),
delstat_6 = nullif(@delstat_6,''),
delstat_7 = nullif(@delstat_7,''),
delstat_8 = nullif(@delstat_8,''),
delstat_9 = nullif(@delstat_9,''),
detdur = nullif(@detdur,''),
detndate = nullif(@detndate,''),
diag_01 = nullif(@diag_01,''),
diag_02 = nullif(@diag_02,''),
diag_03 = nullif(@diag_03,''),
diag_04 = nullif(@diag_04,''),
diag_05 = nullif(@diag_05,''),
diag_06 = nullif(@diag_06,''),
diag_07 = nullif(@diag_07,''),
diag_08 = nullif(@diag_08,''),
diag_09 = nullif(@diag_09,''),
diag_10 = nullif(@diag_10,''),
diag_11 = nullif(@diag_11,''),
diag_12 = nullif(@diag_12,''),
diag_13 = nullif(@diag_13,''),
diag_14 = nullif(@diag_14,''),
diag_15 = nullif(@diag_15,''),
diag_16 = nullif(@diag_16,''),
diag_17 = nullif(@diag_17,''),
diag_18 = nullif(@diag_18,''),
diag_19 = nullif(@diag_19,''),
diag_20 = nullif(@diag_20,''),
diag_3_concat = nullif(@diag_3_concat,''),
diag_4_concat = nullif(@diag_4_concat,''),
diag_count = nullif(@diag_count,''),
disdate = nullif(@disdate,''),
disdest = nullif(@disdest,''),
dismeth = nullif(@dismeth,''),
disreadydate = nullif(@disreadydate,''),
domproc = nullif(@domproc,''),
earldatoff = nullif(@earldatoff,''),
elecdate = nullif(@elecdate,''),
elecdur = nullif(@elecdur,''),
elecdur_calc = nullif(@elecdur_calc,''),
endage = nullif(@endage,''),
epidur = nullif(@epidur,''),
epiend = nullif(@epiend,''),
epikey = nullif(@epikey,''),
epiorder = nullif(@epiorder,''),
epistart = nullif(@epistart,''),
epistat = nullif(@epistat,''),
epitype = nullif(@epitype,''),
ethnos = nullif(@ethnos,''),
ethraw = nullif(@ethraw,''),
fae = nullif(@fae,''),
fae_emergency = nullif(@fae_emergency,''),
fce = nullif(@fce,''),
fde = nullif(@fde,''),
firstreg = nullif(@firstreg,''),
fyear = nullif(@fyear,''),
gestat_1 = nullif(@gestat_1,''),
gestat_2 = nullif(@gestat_2,''),
gestat_3 = nullif(@gestat_3,''),
gestat_4 = nullif(@gestat_4,''),
gestat_5 = nullif(@gestat_5,''),
gestat_6 = nullif(@gestat_6,''),
gestat_7 = nullif(@gestat_7,''),
gestat_8 = nullif(@gestat_8,''),
gestat_9 = nullif(@gestat_9,''),
gortreat = nullif(@gortreat,''),
gpprac = nullif(@gpprac,''),
gppracha = nullif(@gppracha,''),
gppracro = nullif(@gppracro,''),
gpprpct = nullif(@gpprpct,''),
gpprstha = nullif(@gpprstha,''),
hatreat = nullif(@hatreat,''),
hneoind = nullif(@hneoind,''),
hrg40 = nullif(@hrg40,''),
hrglate35 = nullif(@hrglate35,''),
hrgnhs = nullif(@hrgnhs,''),
hrgnhsvn = nullif(@hrgnhsvn,''),
imd04 = nullif(@imd04,''),
imd04_decile = nullif(@imd04_decile,''),
imd04c = nullif(@imd04c,''),
imd04ed = nullif(@imd04ed,''),
imd04em = nullif(@imd04em,''),
imd04hd = nullif(@imd04hd,''),
imd04hs = nullif(@imd04hs,''),
imd04i = nullif(@imd04i,''),
imd04ia = nullif(@imd04ia,''),
imd04ic = nullif(@imd04ic,''),
imd04le = nullif(@imd04le,''),
imd04rk = nullif(@imd04rk,''),
intmanig = nullif(@intmanig,''),
lsoa01 = nullif(@lsoa01,''),
lsoa11 = nullif(@lsoa11,''),
mainspef = nullif(@mainspef,''),
marstat = nullif(@marstat,''),
matage = nullif(@matage,''),
maternity_episode_type = nullif(@maternity_episode_type,''),
mentcat = nullif(@mentcat,''),
msoa01 = nullif(@msoa01,''),
msoa11 = nullif(@msoa11,''),
mydob = nullif(@mydob,''),
neocare = nullif(@neocare,''),
neodur = nullif(@neodur,''),
newnhsno_check = nullif(@newnhsno_check,''),
nhsnoind = nullif(@nhsnoind,''),
numbaby = nullif(@numbaby,''),
numpreg = nullif(@numpreg,''),
numtailb = nullif(@numtailb,''),
oacode6 = nullif(@oacode6,''),
opcs43 = nullif(@opcs43,''),
opdate_01 = nullif(@opdate_01,''),
opdate_02 = nullif(@opdate_02,''),
opdate_03 = nullif(@opdate_03,''),
opdate_04 = nullif(@opdate_04,''),
opdate_05 = nullif(@opdate_05,''),
opdate_06 = nullif(@opdate_06,''),
opdate_07 = nullif(@opdate_07,''),
opdate_08 = nullif(@opdate_08,''),
opdate_09 = nullif(@opdate_09,''),
opdate_10 = nullif(@opdate_10,''),
opdate_11 = nullif(@opdate_11,''),
opdate_12 = nullif(@opdate_12,''),
opdate_13 = nullif(@opdate_13,''),
opdate_14 = nullif(@opdate_14,''),
opdate_15 = nullif(@opdate_15,''),
opdate_16 = nullif(@opdate_16,''),
opdate_17 = nullif(@opdate_17,''),
opdate_18 = nullif(@opdate_18,''),
opdate_19 = nullif(@opdate_19,''),
opdate_20 = nullif(@opdate_20,''),
opdate_21 = nullif(@opdate_21,''),
opdate_22 = nullif(@opdate_22,''),
opdate_23 = nullif(@opdate_23,''),
opdate_24 = nullif(@opdate_24,''),
operstat = nullif(@operstat,''),
opertn_01 = nullif(@opertn_01,''),
opertn_02 = nullif(@opertn_02,''),
opertn_03 = nullif(@opertn_03,''),
opertn_04 = nullif(@opertn_04,''),
opertn_05 = nullif(@opertn_05,''),
opertn_06 = nullif(@opertn_06,''),
opertn_07 = nullif(@opertn_07,''),
opertn_08 = nullif(@opertn_08,''),
opertn_09 = nullif(@opertn_09,''),
opertn_10 = nullif(@opertn_10,''),
opertn_11 = nullif(@opertn_11,''),
opertn_12 = nullif(@opertn_12,''),
opertn_13 = nullif(@opertn_13,''),
opertn_14 = nullif(@opertn_14,''),
opertn_15 = nullif(@opertn_15,''),
opertn_16 = nullif(@opertn_16,''),
opertn_17 = nullif(@opertn_17,''),
opertn_18 = nullif(@opertn_18,''),
opertn_19 = nullif(@opertn_19,''),
opertn_20 = nullif(@opertn_20,''),
opertn_21 = nullif(@opertn_21,''),
opertn_22 = nullif(@opertn_22,''),
opertn_23 = nullif(@opertn_23,''),
opertn_24 = nullif(@opertn_24,''),
opertn_3_concat = nullif(@opertn_3_concat,''),
opertn_4_concat = nullif(@opertn_4_concat,''),
opertn_count = nullif(@opertn_count,''),
orgpppid = nullif(@orgpppid,''),
partyear = nullif(@partyear,''),
pcfound = nullif(@pcfound,''),
pcgcode = nullif(@pcgcode,''),
pcgorig = nullif(@pcgorig,''),
pcon = nullif(@pcon,''),
pcon_ons = nullif(@pcon_ons,''),
pconsult = nullif(@pconsult,''),
pctcode_his = nullif(@pctcode_his,''),
pctcode02 = nullif(@pctcode02,''),
pctcode06 = nullif(@pctcode06,''),
pctnhs = nullif(@pctnhs,''),
pctorig_his = nullif(@pctorig_his,''),
pctorig02 = nullif(@pctorig02,''),
pctorig06 = nullif(@pctorig06,''),
pcttreat = nullif(@pcttreat,''),
posopdur = nullif(@posopdur,''),
postdist = nullif(@postdist,''),
postdur = nullif(@postdur,''),
preferer = nullif(@preferer,''),
preggmp = nullif(@preggmp,''),
preopdur = nullif(@preopdur,''),
primercp = nullif(@primercp,''),
procode = nullif(@procode,''),
procode3 = nullif(@procode3,''),
procode5 = nullif(@procode5,''),
procodet = nullif(@procodet,''),
protype = nullif(@protype,''),
provspnops = nullif(@provspnops,''),
purcode = nullif(@purcode,''),
purro = nullif(@purro,''),
purstha = nullif(@purstha,''),
purval = nullif(@purval,''),
referorg = nullif(@referorg,''),
rescty = nullif(@rescty,''),
rescty_ons = nullif(@rescty_ons,''),
resgor = nullif(@resgor,''),
resgor_ons = nullif(@resgor_ons,''),
resha = nullif(@resha,''),
resladst = nullif(@resladst,''),
respct_his = nullif(@respct_his,''),
respct02 = nullif(@respct02,''),
respct06 = nullif(@respct06,''),
resro = nullif(@resro,''),
resstha_his = nullif(@resstha_his,''),
resstha02 = nullif(@resstha02,''),
resstha06 = nullif(@resstha06,''),
rotreat = nullif(@rotreat,''),
rttperend = nullif(@rttperend,''),
rttperstart = nullif(@rttperstart,''),
rttperstat = nullif(@rttperstat,''),
rururb_ind = nullif(@rururb_ind,''),
sender = nullif(@sender,''),
sex = nullif(@sex,''),
sexbaby_1 = nullif(@sexbaby_1,''),
sexbaby_2 = nullif(@sexbaby_2,''),
sexbaby_3 = nullif(@sexbaby_3,''),
sexbaby_4 = nullif(@sexbaby_4,''),
sexbaby_5 = nullif(@sexbaby_5,''),
sexbaby_6 = nullif(@sexbaby_6,''),
sexbaby_7 = nullif(@sexbaby_7,''),
sexbaby_8 = nullif(@sexbaby_8,''),
sexbaby_9 = nullif(@sexbaby_9,''),
sitetret = nullif(@sitetret,''),
spelbgin = nullif(@spelbgin,''),
speldur = nullif(@speldur,''),
spelend = nullif(@spelend,''),
startage = nullif(@startage,''),
sthatret = nullif(@sthatret,''),
subdate = nullif(@subdate,''),
suscorehrg = nullif(@suscorehrg,''),
sushrg = nullif(@sushrg,''),
sushrgvers = nullif(@sushrgvers,''),
suslddate = nullif(@suslddate,''),
susrecid = nullif(@susrecid,''),
susspellid = nullif(@susspellid,''),
tokenid = nullif(@tokenid,''),
tretspef = nullif(@tretspef,''),
vind = nullif(@vind,''),
waitdays = nullif(@waitdays,''),
waitlist = nullif(@waitlist,''),
ward91 = nullif(@ward91,''),
ward98 = nullif(@ward98,''),
wardstrt = nullif(@wardstrt,''),
well_baby_ind = nullif(@well_baby_ind,'')
;

-- check head of data looks alright
SELECT * FROM hes_ons.APC_2223 LIMIT 100;

--create indexes on ID variable and keys

CREATE INDEX tpid ON hes_ons.APC_2223 (tokenid);
CREATE INDEX epikey on hes_ons.APC_2223 (epikey);
CREATE INDEX aekey on hes_ons.APC_2223 (aekey);
CREATE INDEX susreckey on hes_ons.APC_2223 (susrecid);

-- clean variables
--remove stray spaces, dashes, tildes and dots from diagnosis codes
SET sql_safe_updates = 0;

UPDATE hes_ons.APC_2223
SET 
    diag_01 = if(length(diag_01) = 5, diag_01 = NULL, replace(replace(replace(replace(diag_01, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_02 = if(length(diag_02) = 5, diag_02 = NULL, replace(replace(replace(replace(diag_02, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_03 = if(length(diag_03) = 5, diag_03 = NULL, replace(replace(replace(replace(diag_03, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_04 = if(length(diag_04) = 5, diag_04 = NULL, replace(replace(replace(replace(diag_04, ' ', ''), '-', ''),'.',''), '~', '')),
	diag_05 = if(length(diag_05) = 5, diag_05 = NULL, replace(replace(replace(replace(diag_05, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_06 = if(length(diag_06) = 5, diag_06 = NULL, replace(replace(replace(replace(diag_06, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_07 = if(length(diag_07) = 5, diag_07 = NULL, replace(replace(replace(replace(diag_07, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_08 = if(length(diag_08) = 5, diag_08 = NULL, replace(replace(replace(replace(diag_08, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_09 = if(length(diag_09) = 5, diag_09 = NULL, replace(replace(replace(replace(diag_09, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_10 = if(length(diag_10) = 5, diag_10 = NULL, replace(replace(replace(replace(diag_10, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_11 = if(length(diag_11) = 5, diag_11 = NULL, replace(replace(replace(replace(diag_11, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_12 = if(length(diag_12) = 5, diag_12 = NULL, replace(replace(replace(replace(diag_12, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_13 = if(length(diag_13) = 5, diag_13 = NULL, replace(replace(replace(replace(diag_13, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_14 = if(length(diag_14) = 5, diag_14 = NULL, replace(replace(replace(replace(diag_14, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_15 = if(length(diag_15) = 5, diag_15 = NULL, replace(replace(replace(replace(diag_15, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_16 = if(length(diag_16) = 5, diag_16 = NULL, replace(replace(replace(replace(diag_16, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_17 = if(length(diag_17) = 5, diag_17 = NULL, replace(replace(replace(replace(diag_17, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_18 = if(length(diag_18) = 5, diag_18 = NULL, replace(replace(replace(replace(diag_18, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_19 = if(length(diag_19) = 5, diag_19 = NULL, replace(replace(replace(replace(diag_19, ' ', ''), '-', ''),'.',''), '~', '')),
    diag_20 = if(length(diag_20) = 5, diag_20 = NULL, replace(replace(replace(replace(diag_20, ' ', ''), '-', ''),'.',''), '~', ''))
    ;

-- remove trailing X's 
UPDATE hes_ons.APC_2223
SET 
    diag_01 = if(substring(diag_01, 4, 1) = 'X', substring(diag_01, 1, 3), diag_01),
    diag_02 = if(substring(diag_02, 4, 1) = 'X', substring(diag_02, 1, 3), diag_02),
    diag_03 = if(substring(diag_03, 4, 1) = 'X', substring(diag_03, 1, 3), diag_03),
    diag_04 = if(substring(diag_04, 4, 1) = 'X', substring(diag_04, 1, 3), diag_04),
    diag_05 = if(substring(diag_05, 4, 1) = 'X', substring(diag_05, 1, 3), diag_05),
    diag_06 = if(substring(diag_06, 4, 1) = 'X', substring(diag_06, 1, 3), diag_06),
    diag_07 = if(substring(diag_07, 4, 1) = 'X', substring(diag_07, 1, 3), diag_07),
    diag_08 = if(substring(diag_08, 4, 1) = 'X', substring(diag_08, 1, 3), diag_08),
    diag_09 = if(substring(diag_09, 4, 1) = 'X', substring(diag_09, 1, 3), diag_09),
    diag_10 = if(substring(diag_10, 4, 1) = 'X', substring(diag_10, 1, 3), diag_10),
    diag_11 = if(substring(diag_11, 4, 1) = 'X', substring(diag_11, 1, 3), diag_11),
    diag_12 = if(substring(diag_12, 4, 1) = 'X', substring(diag_12, 1, 3), diag_12),
    diag_13 = if(substring(diag_13, 4, 1) = 'X', substring(diag_13, 1, 3), diag_13),
    diag_14 = if(substring(diag_14, 4, 1) = 'X', substring(diag_14, 1, 3), diag_14),
    diag_15 = if(substring(diag_15, 4, 1) = 'X', substring(diag_15, 1, 3), diag_15),
    diag_16 = if(substring(diag_16, 4, 1) = 'X', substring(diag_16, 1, 3), diag_16),
    diag_17 = if(substring(diag_17, 4, 1) = 'X', substring(diag_17, 1, 3), diag_17),
    diag_18 = if(substring(diag_18, 4, 1) = 'X', substring(diag_18, 1, 3), diag_18),
    diag_19 = if(substring(diag_19, 4, 1) = 'X', substring(diag_19, 1, 3), diag_19),
    diag_20 = if(substring(diag_20, 4, 1) = 'X', substring(diag_20, 1, 3), diag_20)
;

--Use the following SQL to remove unnecessary characters from opertn (' ','-' and ','):

UPDATE hes_ons.APC_2223
SET 
    opertn_01 = if(length(opertn_01) = 1, opertn_01 = NULL, replace(replace(replace(opertn_01, ' ', ''), '-', ''),'.','')),
    opertn_02 = if(length(opertn_02) = 1, opertn_02 = NULL, replace(replace(replace(opertn_02, ' ', ''), '-', ''),'.','')),
    opertn_03 = if(length(opertn_03) = 1, opertn_03 = NULL, replace(replace(replace(opertn_03, ' ', ''), '-', ''),'.','')),
    opertn_04 = if(length(opertn_04) = 1, opertn_04 = NULL, replace(replace(replace(opertn_04, ' ', ''), '-', ''),'.','')),
	opertn_05 = if(length(opertn_05) = 1, opertn_05 = NULL, replace(replace(replace(opertn_05, ' ', ''), '-', ''),'.','')),
    opertn_06 = if(length(opertn_06) = 1, opertn_06 = NULL, replace(replace(replace(opertn_06, ' ', ''), '-', ''),'.','')),
    opertn_07 = if(length(opertn_07) = 1, opertn_07 = NULL, replace(replace(replace(opertn_07, ' ', ''), '-', ''),'.','')),
    opertn_08 = if(length(opertn_08) = 1, opertn_08 = NULL, replace(replace(replace(opertn_08, ' ', ''), '-', ''),'.','')),
    opertn_09 = if(length(opertn_09) = 1, opertn_09 = NULL, replace(replace(replace(opertn_09, ' ', ''), '-', ''),'.','')),
    opertn_10 = if(length(opertn_10) = 1, opertn_10 = NULL, replace(replace(replace(opertn_10, ' ', ''), '-', ''),'.','')),
    opertn_11 = if(length(opertn_11) = 1, opertn_11 = NULL, replace(replace(replace(opertn_11, ' ', ''), '-', ''),'.','')),
    opertn_12 = if(length(opertn_12) = 1, opertn_12 = NULL, replace(replace(replace(opertn_12, ' ', ''), '-', ''),'.','')),
    opertn_13 = if(length(opertn_13) = 1, opertn_13 = NULL, replace(replace(replace(opertn_13, ' ', ''), '-', ''),'.','')),
    opertn_14 = if(length(opertn_14) = 1, opertn_14 = NULL, replace(replace(replace(opertn_14, ' ', ''), '-', ''),'.','')),
    opertn_15 = if(length(opertn_15) = 1, opertn_15 = NULL, replace(replace(replace(opertn_15, ' ', ''), '-', ''),'.','')),
    opertn_16 = if(length(opertn_16) = 1, opertn_16 = NULL, replace(replace(replace(opertn_16, ' ', ''), '-', ''),'.','')),
    opertn_17 = if(length(opertn_17) = 1, opertn_17 = NULL, replace(replace(replace(opertn_17, ' ', ''), '-', ''),'.','')),
    opertn_18 = if(length(opertn_18) = 1, opertn_18 = NULL, replace(replace(replace(opertn_18, ' ', ''), '-', ''),'.','')),
    opertn_19 = if(length(opertn_19) = 1, opertn_19 = NULL, replace(replace(replace(opertn_19, ' ', ''), '-', ''),'.','')),
    opertn_20 = if(length(opertn_20) = 1, opertn_20 = NULL, replace(replace(replace(opertn_20, ' ', ''), '-', ''),'.','')),
	opertn_21 = if(length(opertn_21) = 1, opertn_21 = NULL, replace(replace(replace(opertn_21, ' ', ''), '-', ''),'.','')),
	opertn_22 = if(length(opertn_22) = 1, opertn_22 = NULL, replace(replace(replace(opertn_22, ' ', ''), '-', ''),'.','')),
	opertn_23 = if(length(opertn_23) = 1, opertn_23 = NULL, replace(replace(replace(opertn_23, ' ', ''), '-', ''),'.','')),
	opertn_24 = if(length(opertn_24) = 1, opertn_24 = NULL, replace(replace(replace(opertn_24, ' ', ''), '-', ''),'.',''))
;

-- Create date variable from month and year of birth (mydob), set to the 15th for everyone
-- This makes creating some extracts, based on birth years / months a bit easier
ALTER TABLE hes_ons.APC_2223 ADD mydob_15 date;

UPDATE hes_ons.APC_2223
SET 
	mydob_15 = if(mydob is NULL, NULL, if(length(mydob) = 5, cast(concat(substring(mydob, 2, 4), concat('-0',concat(substring(mydob, 1, 1), '-15'))) as date), cast(concat(substring(mydob, 3, 4), concat('-',concat(substring(mydob, 1, 2), '-15'))) as date)))
;

-- Convert deprivation into codes (imd04_decile) into intergers 
ALTER TABLE hes_ons.APC_2223
	ADD imd04_decile_cat smallint;
    
UPDATE hes_ons.APC_2223
	SET
	imd04_decile_cat = 	if(imd04_decile = 'Most deprived 10%', '1',
					if(imd04_decile = 'More deprived 10-20%', '2', 
					if(imd04_decile = 'More deprived 20-30%', '3', 
					if(imd04_decile = 'More deprived 30-40%', '4', 
					if(imd04_decile = 'More deprived 40-50%', '5', 
					if(imd04_decile = 'Less deprived 40-50%', '6', 
					if(imd04_decile = 'Less deprived 30-40%', '7', 
					if(imd04_decile = 'Less deprived 20-30%', '8', 
					if(imd04_decile = 'Less deprived 10-20%', '9', '10')))))))))
;

-- Clean cause codes (remove ' ', ',' '-') 

UPDATE hes_ons.APC_2223
set 
    cause = if(length(cause) = 1, NULL, replace(replace(replace(cause, ' ', ''), '-', ''),'.',''))
;

-- Add HES-year variable
ALTER TABLE ons.APC_2223 
	ADD hesyr year;

UPDATE hes_ons.APC_2223
SET 
	hesyr = 2022
;