/*
MySQL script (Workbench 8) to upload raw text files as received by NHS England 

This script sets up individual level Outpatient(OP) Hospital Episode Statistics (HES) data 
This data release was approved as part of NIC-393510
Data was received as pipe-delimited flat text files for each financial year  

Editor: Linda Wijlaars
Version: 2023_1
Date: 16 January 2024
Original author: Grant Thiltgen
*/

CREATE TABLE hes_ons.OP_2223 (
activage smallint,
admincat smallint,
apptage smallint,
apptage_calc double,
apptdate date,
at_gp_practice char(3),
at_residence char(3),
at_treatment char(3), 
atentype  smallint,
attended smallint,
attendkey varchar(19),
attendkey_flag varchar(2),
babyage smallint, 
cannet char(3), 
canreg varchar(5), 
carersi smallint, 
ccg_gp_practice varchar(5),
ccg_residence varchar(5), 
ccg_responsibility varchar(5),
ccg_responsibility_origin smallint,
ccg_treatment varchar(5), 
ccg_treatment_origin smallint,
cr_gp_practice char(3),
cr_residence char(3),
cr_treatment char(3),
csnum varchar(6), 
currward char(2), 
currward_ons varchar(9),
diag_01 varchar(6),
diag_02 varchar(6),
diag_03 varchar(6),
diag_04 varchar(6),
diag_05 varchar(6),
diag_06 varchar(6),
diag_07 varchar(6),
diag_08 varchar(6),
diag_09 varchar(6),
diag_10 varchar(6),
diag_11 varchar(6),
diag_12 varchar(6),
diag_count smallint, 
dnadate date, 
earldatoff date,
ethnos varchar(5),
ethrawl varchar(5), 
firstatt varchar(5), 
fyear mediumint,
gortreat char(1), 
gpprac char(6), 
gppracha char(3), 
gppracro char(3), 
gpprpct varchar(5), 
gpprstha char(3), 
hatreat char(3), 
hrgnhs varchar(5),
hrgnhsvn varchar(5), 
imd04 double,
imd04_decile varchar(30),
imd04c double,
imd04ed double,
imd04em double,
imd04hd double,
imd04hs double,
imd04i double,
imd04ia double, 
imd04ic double, 
imd04le double,
imd04rk mediumint,
locclass smallint,
loctype smallint, 
lsoa01 char(9),
lsoa11 char(9), 
mainspef varchar(5), 
marstat varchar(5), 
msoa01 char(9),
msoa11 char(9),
mydob mediumint,
newnhsno_check varchar(2),
nhsnoind varchar(12), 
nodiags smallint,
noprocs smallint,
oacode6 char(6), 
opcs43 varchar(5), 
operstat varchar(5), 
opertn_01 char(4),
opertn_02 char(4),
opertn_03 char(4),
opertn_04 char(4),
opertn_05 char(4),
opertn_06 char(4),
opertn_07 char(4),
opertn_08 char(4),
opertn_09 char(4),
opertn_10 char(4),
opertn_11 char(4),
opertn_12 char(4),
opertn_13 char(4),
opertn_14 char(4),
opertn_15 char(4), 
opertn_16 char(4),
opertn_17 char(4),
opertn_18 char(4),
opertn_19 char(4),
opertn_20 char(4),
opertn_21 char(4),
opertn_22 char(4),
opertn_23 char(4),
opertn_24 char(4),
orgpppid varchar(6),
outcome smallint,
partyear mediumint,
pcfound char(1),
pcon char(3), 
pcon_ons varchar(9),
pconsult char(16), 
pctcode_his varchar(5), 
pctcode02 varchar(5), 
pctcode06 varchar(5), 
pctnhs varchar(5),
pctorig_his smallint,
pctorig02 smallint,
pctorig06 smallint,
pcttreat varchar(5), 
postdist char(4),
preferer char(16), 
preggmp char(16), 
primerecp varchar(5),
priority smallint,
procode varchar(5), 
procode3 varchar(5),
procode5 varchar(5), 
procodet varchar(5), 
protype varchar(16), 
purcode varchar(5), 
purstha char(3), 
purval smallint,
referorg char(6), 
refsourc smallint,
reqdate date,
rescty varchar(5), 
rescty_ons varchar(9),
resgor char(1), 
resgor_ons varchar(9),
resha char(3), 
resladst char(4), 
resladst_ons char(9), 
respct_his varchar(5), 
respct02 varchar(5),
respct06 varchar(5), 
resro char(3), 
resstha_his char(3), 
resstha02 char(3), 
resstha06 char(3), 
rotreat char(3), 
rttperend date,
rttperstart date, 
rttperstat smallint, 
rururb_ind smallint, 
sender varchar(5), 
servtype smallint,
sex  smallint,
sitetret varchar(5), 
stafftyp  smallint,
sthatret char(3), 
subdate date,
sushrg char(5),
sushrgvers smallint, 
suslddate date,
susrecid varchar(19),
susspellid varchar(19),
tokenid char(15),
tretspef varchar(5), 
wait_ind smallint,
waitdays smallint,
waiting smallint,
ward91 char(6)
)
;

LOAD DATA LOCAL INFILE '[filepath]/Data/OP/NIC393510_HES_OP_202299.txt'
INTO TABLE hes_ons.OP_2223
fields terminated by "|"
lines terminated by "\n"
ignore 1 lines
(@activage, @admincat, 	@apptage, 	@apptage_calc, @apptdate, 	@at_gp_practice, 	@at_residence, 	@at_treatment, 	@atentype, 	@attended, @attendkey, 	@attendkey_flag,	
@babyage, 	@cannet, 	
@canreg, 	@carersi, 	@ccg_gp_practice, 	@ccg_residence, 	@ccg_responsibility, 	@ccg_responsibility_origin, 	@ccg_treatment, 	@ccg_treatment_origin, 	
@cr_gp_practice, 	@cr_residence, 	@cr_treatment, 	@csnum, 	@currward, 	@currward_ons, 
@diag_01, 	@diag_02, 	@diag_03, 	@diag_04, 	@diag_05, 	@diag_06, 	@diag_07, 	@diag_08, 	
@diag_09, 	@diag_10, 	@diag_11, 	@diag_12, 	@diag_count, @dnadate,  	
@earldatoff, @ethnos, 	@ethrawl, 	@firstatt, 	@fyear, 	@gortreat, 	@gpprac, 	@gppracha, 	@gppracro, 	@gpprpct, 	
@gpprstha, 	@hatreat, 	@hrgnhs, 	@hrgnhsvn, 	@imd04, 	@imd04_decile, 	@imd04c, 	@imd04ed, 	@imd04em, 	@imd04hd, 	@imd04hs, 	@imd04i, 	@imd04ia, 	@imd04ic, 	
@imd04le, 	@imd04rk, 	
@locclass, @loctype, @lsoa01, 	@lsoa11, 	@mainspef, 	@marstat, 	@msoa01, 	@msoa11, 	@mydob, 	
@newnhsno_check, @nhsnoind, 	@nodiags, @noprocs, 
@oacode6, 	@opcs43, 	@operstat, 	@opertn_01, 	
@opertn_02, 	@opertn_03, 	@opertn_04, 	@opertn_05, 	@opertn_06, 	@opertn_07, 	@opertn_08, 	@opertn_09, 	@opertn_10, 	@opertn_11, 	@opertn_12, 	
@opertn_13, 	@opertn_14, 	@opertn_15, 	@opertn_16, 	@opertn_17, 	@opertn_18, 	@opertn_19, 	@opertn_20, 	@opertn_21, 	@opertn_22, 	@opertn_23, 	
@opertn_24, 	@orgpppid, @outcome, 	
@partyear, 	@pcfound, 	@pcon, 	@pcon_ons, @pconsult, 	@pctcode_his, 	@pctcode02, 	@pctcode06, 	@pctnhs, @pctorig_his, 	@pctorig02, 	@pctorig06, 	
@pcttreat, 	@postdist, 	@preferer, 	@preggmp, 	@primerecp, @priority, 	@procode, 	@procode3, 	@procode5, @procodet, 	@protype, 	@purcode, 	@purstha, 	@purval, 	@referorg, 	@refsourc, 	
@reqdate, 	@rescty, 	@rescty_ons, @resgor, @resgor_ons,	@resha, 	@resladst, 	 @resladst_ons, @respct_his, 	@respct02, 	@respct06, 	@resro, 	@resstha_his, 	@resstha02, 	@resstha06, 	@rotreat, 	
@rttperend, @rttperstart, @rttperstat,
@rururb_ind, 	@sender, 	@servtype, 	@sex, 	@sitetret, 	@stafftyp, 	@sthatret, 	@subdate, 	@sushrg, 	@sushrgvers, @suslddate, @susrecid, @susspellid, @tokenid, 	@tretspef, 	@wait_ind, 	@waitdays, 	@waiting, @ward91)
SET
activage = nullif(@activage,''),
admincat = nullif(@admincat,''),
apptage = nullif(@apptage,''),
apptage_calc = nullif(@apptage_calc,''),
apptdate = nullif(@apptdate,''),
at_gp_practice = nullif(@at_gp_practice,''),
at_residence = nullif(@at_residence,''),
at_treatment = nullif(@at_treatment,''),
atentype = nullif(@atentype,''),
attended = nullif(@attended,''),
attendkey = nullif(@attendkey,''),
attendkey_flag = nullif(@attendkey_flag,''),
babyage = nullif(@babyage,''),
cannet = nullif(@cannet,''),
canreg = nullif(@canreg,''),
carersi = nullif(@carersi,''),
ccg_gp_practice = nullif(@ccg_gp_practice,''),
ccg_residence = nullif(@ccg_residence,''),
ccg_responsibility = nullif(@ccg_responsibility,''),
ccg_responsibility_origin = nullif(@ccg_responsibility_origin,''),
ccg_treatment = nullif(@ccg_treatment,''),
ccg_treatment_origin = nullif(@ccg_treatment_origin,''),
cr_gp_practice = nullif(@cr_gp_practice,''),
cr_residence = nullif(@cr_residence,''),
cr_treatment = nullif(@cr_treatment,''),
csnum = nullif(@csnum,''),
currward = nullif(@currward,''),
currward_ons = nullif(@currward_ons,''),
diag_01 = nullif(@diag_01,''),
diag_02 = nullif(@diag_02,''),
diag_03 = nullif(@diag_03,''),
diag_04 = nullif(@diag_04,''),
diag_05 = nullif(@diag_05,''),
diag_06 = nullif(@diag_06,''),
diag_07 = nullif(@diag_07,''),
diag_08 = nullif(@diag_08,''),
diag_09 = nullif(@diag_09,''),
diag_10 = nullif(@diag_10,''),
diag_11 = nullif(@diag_11,''),
diag_12 = nullif(@diag_12,''),
diag_count = nullif(@diag_count,''),
dnadate = nullif(@dnadate,''),
earldatoff = nullif(@earldatoff,''),
ethnos = nullif(@ethnos,''),
ethrawl = nullif(@ethrawl,''),
firstatt = nullif(@firstatt,''),
fyear = nullif(@fyear,''),
gortreat = nullif(@gortreat,''),
gpprac = nullif(@gpprac,''),
gppracha = nullif(@gppracha,''),
gppracro = nullif(@gppracro,''),
gpprpct = nullif(@gpprpct,''),
gpprstha = nullif(@gpprstha,''),
hatreat = nullif(@hatreat,''),
hrgnhs = nullif(@hrgnhs,''),
hrgnhsvn = nullif(@hrgnhsvn,''),
imd04 = nullif(@imd04,''),
imd04_decile = nullif(@imd04_decile,''),
imd04c = nullif(@imd04c,''),
imd04ed = nullif(@imd04ed,''),
imd04em = nullif(@imd04em,''),
imd04hd = nullif(@imd04hd,''),
imd04hs = nullif(@imd04hs,''),
imd04i = nullif(@imd04i,''),
imd04ia = nullif(@imd04ia,''),
imd04ic = nullif(@imd04ic,''),
imd04le = nullif(@imd04le,''),
imd04rk = nullif(@imd04rk,''),
locclass = nullif(@locclass,''),
loctype = nullif(@loctype,''),
lsoa01 = nullif(@lsoa01,''),
lsoa11 = nullif(@lsoa11,''),
mainspef = nullif(@mainspef,''),
marstat = nullif(@marstat,''),
msoa01 = nullif(@msoa01,''),
msoa11 = nullif(@msoa11,''),
mydob = nullif(@mydob,''),
newnhsno_check = nullif(@newnhsno_check,''),
nhsnoind = nullif(@nhsnoind,''),
nodiags = nullif(@nodiags,''),
noprocs = nullif(@noprocs,''),
oacode6 = nullif(@oacode6,''),
opcs43 = nullif(@opcs43,''),
operstat = nullif(@operstat,''),
opertn_01 = nullif(@opertn_01,''),
opertn_02 = nullif(@opertn_02,''),
opertn_03 = nullif(@opertn_03,''),
opertn_04 = nullif(@opertn_04,''),
opertn_05 = nullif(@opertn_05,''),
opertn_06 = nullif(@opertn_06,''),
opertn_07 = nullif(@opertn_07,''),
opertn_08 = nullif(@opertn_08,''),
opertn_09 = nullif(@opertn_09,''),
opertn_10 = nullif(@opertn_10,''),
opertn_11 = nullif(@opertn_11,''),
opertn_12 = nullif(@opertn_12,''),
opertn_13 = nullif(@opertn_13,''),
opertn_14 = nullif(@opertn_14,''),
opertn_15 = nullif(@opertn_15,''),
opertn_16 = nullif(@opertn_16,''),
opertn_17 = nullif(@opertn_17,''),
opertn_18 = nullif(@opertn_18,''),
opertn_19 = nullif(@opertn_19,''),
opertn_20 = nullif(@opertn_20,''),
opertn_21 = nullif(@opertn_21,''),
opertn_22 = nullif(@opertn_22,''),
opertn_23 = nullif(@opertn_23,''),
opertn_24 = nullif(@opertn_24,''),
orgpppid = nullif(@orgpppid,''),
outcome = nullif(@outcome,''),
partyear = nullif(@partyear,''),
pcfound = nullif(@pcfound,''),
pcon = nullif(@pcon,''),
pcon_ons = nullif(@pcon_ons,''),
pconsult = nullif(@pconsult,''),
pctcode_his = nullif(@pctcode_his,''),
pctcode02 = nullif(@pctcode02,''),
pctcode06 = nullif(@pctcode06,''),
pctnhs = nullif(@pctnhs,''),
pctorig_his = nullif(@pctorig_his,''),
pctorig02 = nullif(@pctorig02,''),
pctorig06 = nullif(@pctorig06,''),
pcttreat = nullif(@pcttreat,''),
postdist = nullif(@postdist,''),
preferer = nullif(@preferer,''),
preggmp = nullif(@preggmp,''),
primerecp = nullif(@primerecp,''),
priority = nullif(@priority,''),
procode = nullif(@procode,''),
procode3 = nullif(@procode3,''),
procode5 = nullif(@procode5,''),
procodet = nullif(@procodet,''),
protype = nullif(@protype,''),
purcode = nullif(@purcode,''),
purstha = nullif(@purstha,''),
purval = nullif(@purval,''),
referorg = nullif(@referorg,''),
refsourc = nullif(@refsourc,''),
reqdate = nullif(@reqdate,''),
rescty = nullif(@rescty,''),
rescty_ons = nullif(@rescty_ons,''),
resgor = nullif(@resgor,''),
resgor_ons = nullif(@resgor_ons,''),
resha = nullif(@resha,''),
resladst = nullif(@resladst,''),
resladst_ons = nullif(@resladst_ons,''),
respct_his = nullif(@respct_his,''),
respct02 = nullif(@respct02,''),
respct06 = nullif(@respct06,''),
resro = nullif(@resro,''),
resstha_his = nullif(@resstha_his,''),
resstha02 = nullif(@resstha02,''),
resstha06 = nullif(@resstha06,''),
rotreat = nullif(@rotreat,''),
rttperend = nullif(@rttperend,''),
rttperstart = nullif(@rttperstart,''),
rttperstat = nullif(@rttperstat,''),
rururb_ind = nullif(@rururb_ind,''),
sender = nullif(@sender,''),
servtype = nullif(@servtype,''),
sex = nullif(@sex,''),
sitetret = nullif(@sitetret,''),
stafftyp = nullif(@stafftyp,''),
sthatret = nullif(@sthatret,''),
subdate = nullif(@subdate,''),
sushrg = nullif(@sushrg,''),
sushrgvers = nullif(@sushrgvers,''),
suslddate = nullif(@suslddate,''),
susrecid = nullif(@susrecid,''),
susspellid = nullif(@susspellid,''),
tokenid = nullif(@tokenid,''),
tretspef = nullif(@tretspef,''),
wait_ind = nullif(@wait_ind,''),
waitdays = nullif(@waitdays,''),
waiting = nullif(@waiting,''),
ward91 = nullif(@ward91,'')
;

-- check first 100 rows in case any weird warnings show up in previous step
select * from hes_ons.OP_2223 limit 100;

CREATE INDEX tp_id_op ON hes_ons.OP_2223 (tokenid);
CREATE INDEX attendkey ON hes_ons.OP_2223 (attendkey);

--basic datta cleaning
--remove stray characters from diagnosis codes
UPDATE hes_ons.OP_2223
SET 
    diag_01 = if(length(diag_01) = 1, NULL, replace(replace(diag_01, '-', ''),'.','')),
    diag_02 = if(length(diag_02) = 1, NULL, replace(replace(diag_02, '-', ''),'.','')),
    diag_03 = if(length(diag_03) = 1, NULL, replace(replace(diag_03, '-', ''),'.','')),
    diag_04 = if(length(diag_04) = 1, NULL, replace(replace(diag_04, '-', ''),'.','')),
    diag_05 = if(length(diag_05) = 1, NULL, replace(replace(diag_05, '-', ''),'.','')),
    diag_06 = if(length(diag_06) = 1, NULL, replace(replace(diag_06, '-', ''),'.','')),
    diag_07 = if(length(diag_07) = 1, NULL, replace(replace(diag_07, '-', ''),'.','')),
    diag_08 = if(length(diag_08) = 1, NULL, replace(replace(diag_08, '-', ''),'.','')),
    diag_09 = if(length(diag_09) = 1, NULL, replace(replace(diag_09, '-', ''),'.','')),
    diag_10 = if(length(diag_10) = 1, NULL, replace(replace(diag_10, '-', ''),'.','')),
    diag_11 = if(length(diag_11) = 1, NULL, replace(replace(diag_11, '-', ''),'.','')),
    diag_12 = if(length(diag_12) = 1, NULL, replace(replace(diag_12, '-', ''),'.',''))
;

--add HES year variable 
ALTER TABLE hes_ons.OP_2223
	ADD COLUMN hesyr year
;

UPDATE hes_ons.OP_2223
SET 
	hesyr = 2022
;

--add date variable for month and year of birth (set for 15th of the month for everyone)
ALTER TABLE hes_ons.OP_2223 
	ADD mydob_15 date;

UPDATE hes_ons.OP_2223
SET 
	mydob_15 = if(length(mydob) = 5, cast(concat(substring(mydob, 2, 4), concat('-0',concat(substring(mydob, 1, 1), '-15'))) as date), cast(concat(substring(mydob, 3, 4), concat('-',concat(substring(mydob, 1, 2), '-15'))) as date))
;

--Convert deprivation into codes (imd04_decile) into intergers where

ALTER TABLE hes_ons.OP_2223
	ADD COLUMN imd04_decile_cat smallint;
    
UPDATE hes_ons.OP_2223
SET
	imd04_decile_cat = if(imd04_decile = 'Most deprived 10%', '1',
					if(imd04_decile = 'More deprived 10-20%', '2', 
					if(imd04_decile = 'More deprived 20-30%', '3', 
					if(imd04_decile = 'More deprived 30-40%', '4', 
					if(imd04_decile = 'More deprived 40-50%', '5', 
					if(imd04_decile = 'Less deprived 40-50%', '6', 
					if(imd04_decile = 'Less deprived 30-40%', '7', 
					if(imd04_decile = 'Less deprived 20-30%', '8', 
					if(imd04_decile = 'Less deprived 10-20%', '9', 
					if(imd04_decile = 'Least deprived 10%', '10', NULL))))))))))
;

-- Clean sex codes (convert 0 values to 9 so all years are the same) 

UPDATE hes_ons.OP_2223
SET
	sex = if(sex = '0', '9', sex)
; 

-- Clean ethnos codes
-- Changes the missing ethnos code from 99 back to X to be consistent with previous years.accessible

UPDATE hes_ons.OP_2223
SET 
    ethnos = if(ethnos = '99', 'X', ethnos)
;